### ISSUE TITLE
Fix cors and certificate for make https works good

### ISSUE THREAD

**Issue by bitvalser** [VladimirKhil/SIOnline#103]
You can't login in game if you are using sionline.ru
You have CORS issue bacause you origin don't match with api server url, you shoud provider Access-Control-* headers
https://developer.mozilla.org/ru/docs/Web/HTTP/CORS
![image](https://user-images.githubusercontent.com/40835176/179292314-64715339-4377-47b4-8221-759de8674315.png)

And seems you hav esome problems with https configuration
![image](https://user-images.githubusercontent.com/40835176/179292428-a7740e70-ac44-486c-9f58-0006b855c083.png)

**Comment by VladimirKhil** [comment]
sionline.ru domain is not supported anymore.
