### ISSUE TITLE
Error throws when media plays

### ISSUE THREAD

**Issue by VagrantAI-c** [VladimirKhil/SIOnline#108]
When video or audio question starts, media is not played and next error is being thrown:
https://github.com/VladimirKhil/SIOnline/blob/224f2250e19e8adcadb9b0ee0c6a97bf02d63a17/src/components/gameTable/TableVideo.tsx#L61
<img width="330" alt="image" src="https://user-images.githubusercontent.com/3488005/197872602-00bcfe39-2cb4-482b-8773-f8b10ad90b9d.png">
![image](https://user-images.githubusercontent.com/3488005/197872811-124fedb9-4f86-425f-82d5-54822c2157cc.png)
I might guess that it depends on specific pack, because some packs plays its media normally. Repro pack: https://www.sibrowser.ru/packages/19709 (1st round, 3rd category)
Maybe it's  codec-related bug? I remember having trouble playing 10bit video on some environments.

PS. The error on screenshot might not correlate with the error itself

MacOS 12.6
Chrome 106

**Comment by VladimirKhil** [comment]
I see that audio files in the pack have .wma format. This is Windows-only format not suited for web or for MacOS. It is preferable to use mp3 file format for cross-platform audio.

**Comment by VagrantAI-c** [comment]
Maybe it's worth restricting file formats so we can be sure they are playable on any environment?

**Comment by VladimirKhil** [comment]
> Maybe it's worth restricting file formats so we can be sure they are playable on any environment?

Yeah, I will add warning to SIQuester. I do not think that these formats should be forbidden at all because somebody could use their package with such files in Windows environment only.
