### ISSUE TITLE
Нужно ли показывать предупреждение об использовании Cookies на сайте?

### ISSUE THREAD

**Issue by VladimirKhil** [VladimirKhil/SIOnline#23]
По факту, Cookies не используются, но используется localStorage.

**Comment by bitvalser** [comment]
Скорее всего что да, даже если вы напрямую не используется куки, то это могут делать различный либы, как например баннер с рекламой яндекса. Правда некоторые куки необходимы для правильной работы сайта, как например __cfduid, нужен для защиты сайта от вредоносного трафика, но он анонимизирует его и этот куки не должен попадать под GDPR политику.
Для проверки сайта на соответствие с политикой GDPR я использовал [этот сайт](https://2gdpr.com/) он находит несоответствия на всём домене и как я и думал там есть яндекс метрика.
Я не специалист в этой области и могу ошибаться, но я считаю что показывать баннер стоит хотя бы из-за куки которые устанавливает яндекс.
![image](https://user-images.githubusercontent.com/40835176/99312491-2d371e80-286f-11eb-87b0-df16407fee51.png)

**Comment by VladimirKhil** [comment]
@bitvalser спасибо большое за подробные разъяснения!
