### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by 350str** [VladimirKhil/SIOnline#87]
А контрибьютить совсем нельзя в проект? Хотел залить регулятор громкости для SIOnline и столкнулся с проблемой доступа при пуше ветки.

**Comment by VladimirKhil** [comment]
Можно стандартным способом - создав fork проекта, закоммитив изменения туда и затем создав Pull Request в данный репозиторий.

**Comment by 350str** [comment]
так и сделаю, спасибо)
