### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by 350str** [VladimirKhil/SIOnline#92]
Возникает CORS ошибка при попытке зайти в игру на странице логина. Проблема не только у меня, но и у некоторых друзей (что интересно, не у всех)

![image](https://user-images.githubusercontent.com/58252115/167590690-f7f3716a-d388-4413-8182-b5cb5d889761.png)

**Comment by VladimirKhil** [comment]
В настоящий момент используется один домен для игры, так что проблема должна уйти.
